api/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls import url, include
#from . import views
from .views import ReservationView


urlpatterns = [
    # /api/
    url(r'^$', login_required(ReservationView.as_view())),
    url(r'^login/$', ReservationView.loginView, name='loginView'),
    url(r'^logout/$', ReservationView.logout_view, name='logout_view'),
    #url(r'^edit', views.list, name='list'),
    #url(r'^seat', views.seat, name='seat'),
    url('^(?P<date>\d{4}-\d{2}-\d{2})/$', login_required(ReservationView.as_view())),
    path('remove/<int:id>', ReservationView.remove),
    #path('<int:date>/edit', views.list),
]

daddy/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from api.resources import ReservationResource

reservation_resource = ReservationResource()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(reservation_resource.urls)),
    url(r'^api/', include('api.urls')),
]

api/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
# api/models.py
class Reservation(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    seat = models.IntegerField(
        default='1'
    )
    secret = models.CharField(
        max_length=200
    )
    x = models.FloatField(
        default='0.1',
    )
    y = models.FloatField(
        default='0.1',
    )
    note = models.TextField(
        blank=True
    )
    date = models.CharField(
        max_length=200
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    def __str__(self):
        return '%s %s %s ' % (self.seat, self.secret, self.note)

class ReservationLog(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    res_id = models.IntegerField(
        default='0'
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    creation_date = models.DateTimeField(
        default = timezone.now
    )
    updated_by = models.ForeignKey(
        User,
        related_name="updated_by",
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    res_creator = models.ForeignKey(
        User,
        related_name="res_creator",
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    seat = models.IntegerField(
        default='1'
    )
    secret = models.CharField(
        max_length=200
    )
    x = models.FloatField(
        default='0.1',
    )
    y = models.FloatField(
        default='0.1',
    )
    note = models.TextField(
        blank=True
    )
    date = models.CharField(
        max_length=200
    )

api/forms.py
from django import forms

from .models import Reservation

class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ('seat', 'secret', 'note', 'x', 'y')

api/views.py
import sys
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import redirect
from django.forms import inlineformset_factory
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.views import View
import datetime
from datetime import date, timedelta
from .models import Reservation, ReservationLog
from .forms import ReservationForm
# Create your views here.

class ReservationView(View):
    date = datetime.date.today()
    date = date.strftime('%Y-%m-%d')
    seats = {0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30}
    f = ReservationForm()
    coming_days = []
    for x in range(15):
        day = datetime.date.today() + timedelta(days=x)
        coming_days.append(day)
    current_date = datetime.datetime.strptime(date, '%Y-%m-%d')

    def get(self, request, date=date):
        reservs = Reservation.objects.filter(date__exact=date)
        logs = ReservationLog.objects.all()
        #request.reply_channel.send({'form': f, 'reservs': reservs, 'seats': seats, 'current_date': current_date, 'coming_days': coming_days, 'logs': logs, 'MAX_HOUR': settings.MAX_HOUR, 'MIN_STEPS': settings.MIN_STEPS, 'MAX_RES_TIME': settings.MAX_RES_TIME, 'DEF_RES_TIME': settings.DEF_RES_TIME})
        return render(request, 'reservation/list.html', {'form': self.f, 'reservs': reservs, 'seats': self.seats, 'current_date': self.current_date, 'coming_days': self.coming_days, 'logs': logs, 'MAX_HOUR': settings.MAX_HOUR, 'MIN_STEPS': settings.MIN_STEPS, 'MAX_RES_TIME': settings.MAX_RES_TIME, 'DEF_RES_TIME': settings.DEF_RES_TIME})

    def post(self, request, date=date):
        f = ReservationForm(request.POST)
        if request.POST.get('id'):
            res = Reservation.objects.get(pk=request.POST.get('id'))
            f = ReservationForm(request.POST, instance=res)
            creator = res.creator
        else:
            f = ReservationForm(request.POST)
            creator = User.objects.get(pk=request.POST.get('creator'))
        if f.is_valid():
            res = f.save(commit=False)
            #res.created_at = timezone.now()
            res.date = date
            res.creator = creator
            a = 1
            range_steps = settings.MAX_HOUR/settings.MIN_STEPS+1
            for x in [x * settings.MIN_STEPS for x in range(0, int(range_steps))]:
                if x < res.x:
                    a = x
            b = a + settings.MIN_STEPS
            if b-res.x > res.x-a:
                res.x = a
            else:
                res.x = b
            for y in [y * settings.MIN_STEPS for y in range(0, int(range_steps))]:
                if y < res.y:
                    a = y
            b = a + settings.MIN_STEPS
            if b-res.y > res.y-a:
                res.y = a
            else:
                res.y = b


            if res.y > settings.MAX_HOUR:
                res.y = settings.HOUR
            res.save()
            if request.POST.get('id'):
                res_created = Reservation.objects.get(pk=request.POST.get('id'))
            else:
                res_created = Reservation.objects.latest('id')
            res_log = ReservationLog()
            res_log.res_id = res_created.id
            res_log.created_at = timezone.now()
            res_log.creation_date = res_created.created_at
            res_log.res_creator = res_created.creator
            res_log.updated_by = request.user
            res_log.seat = res_created.seat
            res_log.secret = res_created.secret
            res_log.x = res_created.x
            res_log.y = res_created.y
            res_log.note = res_created.note
            res_log.date = res_created.date
            res_log.save()
        reservs = Reservation.objects.filter(date__exact=date)
        logs = ReservationLog.objects.all()
        return render(request, 'reservation/list.html', {'form': self.f, 'reservs': reservs, 'seats': self.seats, 'current_date': self.current_date, 'coming_days': self.coming_days, 'logs': logs, 'MAX_HOUR': settings.MAX_HOUR, 'MIN_STEPS': settings.MIN_STEPS, 'MAX_RES_TIME': settings.MAX_RES_TIME, 'DEF_RES_TIME': settings.DEF_RES_TIME})


    def loginView(request):
        l = AuthenticationForm()
        today = datetime.date.today()
        today = today.strftime('%Y-%m-%d')
        if request.method == "POST":
            user = request.POST['username']
            passw = request.POST['password']
            user = authenticate(request, username=user, password=passw)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/api/'+today+'/')
            else:
                msg = 'Access denied. Please enter valid access data'
                return render(request, 'account/login.html', {'form': l, 'msg': msg})
        return render(request, 'account/login.html', {'form': l})

    def logout_view(request):
        user = request.user
        logout(request)
        return HttpResponseRedirect('/api/login')

    def remove(request, id=1):
        res = Reservation.objects.get(pk=id)
        res_log = ReservationLog.objects.filter(res_id=id)
        res.delete()
        res_log.delete()
        today = datetime.date.today()
        today = today.strftime('%Y-%m-%d')
        return redirect('/api/'+today, {'res': res})


    # def writeResLog(request, res_created):
    #     res_log = ReservationLog()
    #     res_log.res_id = res_created.id
    #     res_log.created_at = timezone.now()
    #     res_log.creation_date = res_created.created_at
    #     res_log.res_creator = res_created.creator
    #     res_log.updated_by = request.user
    #     res_log.seat = res_created.seat
    #     res_log.secret = res_created.secret
    #     res_log.x = res_created.x
    #     res_log.y = res_created.y
    #     res_log.note = res_created.note
    #     res_log.date = res_created.date
    #     res_log.save()
    #     return True

    #
    # def seat(request):
    #     x=1
    #     for x in range(31):
    #         seat = Seat(number=x, guest_id="", note="")
    #         seat.save()
    #     return True

api/templates/reservation/list.html
{% load mathfilters %}
{% load js %}
{% load intpoint %}
{% load static %}
{% load staticfiles %}

<!--
WHEN changing grid var, for example from 6 hours to 9 hours:

px values, percentages and decimals (db) all derive from hours.
=>
decimal form of 19:00 - 22:15 = 0 - 3.25
decimal form of 19:30 - 00:45 = 0.5 - 5.75

min.steps are at 15min
=> in 6 hours - 1h = 1/6 - 15min = 1h/4 => 15min = 1/24
=> in 9 hours - 1h = 1/9 - 15min = 1h/4 => 15min = 1/36
//using in range(37) ensures looking at the last step as well (if rounding up, could be the last part)

=>
percentage % value for pos of item (given in decimal form)
Q: wich ratio has value to max-value of hours?
A: val/MAX (1.5/6)
in % = 1.5/MAX*100
//in docs defined at
templates/list.html
    - **with left:res.x/9*100, var setup used for width calc
    - left:res.x/9*100, used directly as item.pos.left="" value
    - right:res.y/9*100, used directly as item.pos.right="" value
    - width:res.y/9*100-left**, used directly as item.width="" value
    - res_x = (x/$(this).width()*100)*9/100;, NEW ITEM calc res_x to save in form.input.hidden.x
    - when calc grid size
      - var grid_x = $('td.blocks-container').width()/36;
        grid size is updated if window.size changes, to keep static px value representing 15min steps
    - res_x = Math.round(pos_x/$(this).parent().width()*100)*9/100;, on 'resizestop', 'dragstop'
      // calc values and round => val === db conform
views.py
    - in range(37): creates array with every value that is needed to count to 9(MAX HOUR VALUE), using quarter(0.25, STEP VALUE)steps
    - if res.y > 7 ? res.y = 7,  reservation cant be longer than 7 hous (MAX RES_TIME VALUE)
Style CSS
    - background: lineargradient()...;, background pattern need to be manually adapted if MAX HOUR VAUE or STEPS VALUE CHANGE
percentages are used to calc the grid pattern, e.g grid line every three hours = 33.33%


 -->
<!DOCTYPE html>
<html lang="de-De">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reservationbook: "Die Bar" - 2019</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static '/channels/js/websocketbridge.js' %}" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"   integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="   crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"   integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="   crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
{% if user.is_authenticated %}
<div style="text-align:right; padding:8px 10px;">
    <span><small class="mono">Current user: <b>{{ user.get_username }}</b> | </small></span>
    <a href="/api/logout"><small class="mono">Logout</small></a>
</div>
{% endif %}
<div class="container">
    <h1>Reservations for: {{ current_date|date:'D, d.m.Y'}}</h1>
    <span class="data_toggle"><span class="date_show_txt mono" style="display:none;">Show Datelist</span><span class="date_hide_txt mono" style="display:none;">Hide Datelist</span></span>
    <ul class="date_list">
    {% for day in coming_days%}
        <li class="date_item" style="display:inline-block"><a href="/api/{{ day|date:'Y-m-d' }}/" class="mono">{{ day|date:'D, d.m.Y' }}</a></li>
    {%endfor%}
    </ul>
    <table border="1">
        <thead>
        <tr>
            <th class="left-col">Seat</th>
            <th class="blocks-container">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-4"><time>19:00</time></div>
                                <div class="col-sm-4"><time>20:00</time></div>
                                <div class="col-sm-4"><time>21:00</time></div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-4"><time>22:00</time></div>
                                <div class="col-sm-4"><time>23:00</time></div>
                                <div class="col-sm-4"><time>00:00</time></div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-4"><time>01:00</time></div>
                                <div class="col-sm-4"><time>02:00</time></div>
                                <div class="col-sm-4"><time>03:00</time></div>
                            </div>
                        </div>
                    </div>
                </div>
            </th>
        </tr>
        </thead>
        <tbody>

        {% for seat in seats %}
            <tr tabindex="-1">
                <th class="left-col">{{forloop.counter}}</th>
                <td class="blocks-container">
                    {% for res in reservs %}
                    {%if forloop.parentloop.counter == res.seat%}
                    {% with left=res.x|div:MAX_HOUR|mul:100 %}
                    <div class="form_box_container" tabindex="-1" style="left: {{res.x|div:MAX_HOUR|mul:100|intpoint}}%; right: {{res.y|div:MAX_HOUR|mul:100|intpoint}}%; width: {{res.y|div:MAX_HOUR|mul:100|sub:left|intpoint}}%;">
                    {%endwith%}
                        <form method="POST" class="post-form row">{% csrf_token %}
                            <input type="hidden" name="seat" id="id_seat" value="{{forloop.parentloop.counter}}"/>
                            <input type="hidden" name="id" id="id_id" value="{{res.id}}"/>
                            <input type="hidden" name="x" id="id_x" value="{{res.x}}">
                            <input type="hidden" name="y" id="id_y" value="{{res.y}}">
                            <div class="col-sm-4">{{res.secret}}<input type="text" name="secret" id="id_secret" value="{{res.secret}}"></div>
                            <div class="col-sm-4">{{res.note}}<input type="text" name="note" id="id_note" value="{{res.note}}"></div>
                            <div class="col-sm-4"><button type="submit" class="save btn btn-default">Save</button></div>
                        </form>
                        <div class="log">
                            <h2>Reservation log for {{res.note}}</h2>
                            {% for log in logs %}
                                {% if log.res_id == res.id %}
                                    <p>seat: {{log.seat}}, secret: {{log.secret}}</p>
                                    <p><small>{{log.res_creator}},{{log.updated_by}},{{log.creation_date}},{{log.created_at}}</small></p>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {%endif%}
                    {%endfor%}
                    <form method="POST" class="post-form empty_form">{% csrf_token %}
                        <input type="hidden" name="creator" id="creator" value="{{user.id}}">
                        <input type="hidden" name="seat" id="seat" value="{{forloop.counter}}"/>
                        <div><input type="text" name="secret" id="secret"></div>
                        <div><input type="hidden" name="x" id="x"></div>
                        <div><input type="hidden" name="y" id="y"></div>
                        <div><input type="text" name="note" id="note"></div>
                        <button type="submit" class="save btn btn-default">Save</button>
                    </form>
                </td>
            </tr>
        {%endfor%}
        </tbody>

    </table>

    <ul id="reservationlist"></ul>
    </div>
<script>
document.addEventListener('DOMContentLoaded', function() {
      const webSocketBridge = new channels.WebSocketBridge();
      const nl = document.querySelector("#reservationlist");

      webSocketBridge.connect('/');
      webSocketBridge.listen(function(action, stream) {
        console.log("RESPONSE:", action);
        if(action.event == "New reservation") {
          var el = document.createElement("li");
          el.innerHTML = `New Reservation <b>${action.secret}</b> has been created!`;
          nl.appendChild(el);
        }
      })
      document.ws = webSocketBridge; /* for debugging */
});
$(document).ready(function() {

    var MAX_HOUR = {{ MAX_HOUR|js}}
    var MAX_RES_TIME = {{ MAX_RES_TIME|js}}
    var DEF_RES_TIME = {{ DEF_RES_TIME|js}}
    var MIN_STEPS = {{ MIN_STEPS|js}}

  $('td.blocks-container').find('form.empty_form').hide();
  var cc = 0;
  $('td.blocks-container').on("dblclick", function(e) {
     var el = $(this).find('form.empty_form');
     if(cc == 0){
         var x = e.pageX - $(this).offset().left;
         var y = e.pageY - $(this).offset().top;
         el.css('position', 'absolute');
         el.css("left", x);
         el.css("top", y);
         res_x = (x/$(this).width()*100)*MAX_HOUR/100;
         el.find('input#x').val(res_x);
         var res_y = res_x + DEF_RES_TIME;
         el.find('input#y').val(res_y);
         el.show();
         cc = 1;
     }
   });
   $('td.blocks-container').on("click", function(e) {
       $('form.empty_form').hide();
       $('.log').css('display', 'none');
       cc = 0;
   });

   $('td.blocks-container .form_box_container').on('dblclick', function(e){
       e.stopPropagation();
       $(this).find('.log').show();
   });
   $('td.blocks-container .form_box_container').on('click', function(e){
       e.stopPropagation();
       $(this).focus();
   });
   $('td.blocks-container form.empty_form').on('click', function(e){
       e.stopPropagation();
   });

   $('td.blocks-container .form_box_container').on('keyup', function(e){
       if(e.keyCode == 8){
           // 8 is backspace
          var id =  $(this).find('input#id_id').val();
          var res_note =  $(this).find('input#id_note').val();
          var rem = confirm('Möchten Sie Reservierung für '+ res_note+ ' wirklich löschen?')
            if(rem) {
                window.location.href = "/api/remove/"+id;
            }
       }
   });

    grid_divisor = MAX_HOUR/MIN_STEPS;
    var grid_x = Math.round($('td.blocks-container').width()/grid_divisor);
    console.log(grid_x+" / "+$('td.blocks-container').width()+" / "+MAX_HOUR+" / "+MIN_STEPS);
   $(window).on('resize', function(e){
        grid_x = Math.round($('td.blocks-container').width()/grid_divisor);
        console.log(grid_x);

   });
   $('.form_box_container').resizable({
       containment: "parent",
       //grid: [grid_x, 10],
       handles: "e, w",
   });
   $('.form_box_container').draggable({
       containment: "parent",
       //grid: [grid_x, 10],
       axis: "x",
   });
   $('.form_box_container').on('resizestop', function(e, ui){
        pos_x = ui.position.left;
        res_x = Math.round(pos_x/$(this).parent().width()*100)*MAX_HOUR/100;
        if(res_x == 0){
            res_x = 0.1;
        }
        pos_y = ui.position.left + ui.size.width;
        res_y = Math.round(pos_y/$(this).parent().width()*100)*MAX_HOUR/100;
        $(this).find('button.save').show();
        $(this).find('input#id_x').val(res_x);
        $(this).find('input#id_y').val(res_y);
   });

   $('.form_box_container').on('dragstop', function(e, ui){
        pos_x = ui.position.left;
        console.log(pos_x);
        res_x = Math.round(pos_x/$(this).parent().width()*100)*MAX_HOUR/100;
        console.log(res_x);
        if(res_x == 0){
            res_x = 0.1;
        }
        pos_y = ui.position.left + $(this).width() + 20 //20px padding, if not added it returns y value less than before ->smaller elem;
        console.log($(this).width());
        console.log(pos_y);
        res_y = Math.round(pos_y/$(this).parent().width()*100)*MAX_HOUR/100;
        console.log(res_y);
        $(this).find('button.save').show();
        $(this).find('input#id_x').val(res_x);
        $(this).find('input#id_y').val(res_y);
   });

})
$('input[name="seat"]').hide();

$('.date_list').hide();
$('.date_show_txt').show();
$('.date_show_txt').on('click', function() {
    $('.date_list').show();
    $('.date_show_txt').hide();
    $('.date_hide_txt').show();
});
$('.date_hide_txt').on('click', function() {
    $('.date_list').hide();
    $('.date_show_txt').show();
    $('.date_hide_txt').hide();
});

</script>
</body>
</html>

api/templates/reservation/reservation_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>

    {% block content %}
    <h2>New reservation</h2>
    <p>{{ message }}</p>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}
</body>
</html>